### ISSUE TITLE
Edge에서 5.0 태그 보도록 변경...?

### ISSUE THREAD

**Issue by riseshia** [rorlakr/rails-guides#49]
앞으로는 제대로된 버전관리....를 해봅시다.
이쪽이 번역 차분 관리하기도 편할거구요. ㅇ>-<

**Comment by riseshia** [comment]
after #46

**Comment by riseshia** [comment]
태깅 시작
일단 `ko-5.0.1`
별도의 페이지 생성하는건 천천히....

**Comment by wagurano** [comment]
레일스 버전 별로 서브디렉토리를 만들까요?

예시)
- 지난 버전 rails-guides/guides/source/ko/v5.0
- 현재 버전 rails-guides/guides/source/ko/

**Comment by riseshia** [comment]
저는 포기했습니다. 잘 부탁드립니다 :bow:

**Comment by wagurano** [comment]
시아님 덕분에 5.0까지 잘 봤습니다. 5.1은 번역 예정입니다. 나중에 풀리퀘스트 오면 한번 봐주세요.
